rails_app/config/routes.rb
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'

  get "/sparql-space", :to => "sparql#index"
  
  root :to => "catalog#index"

  resources :accounts, except: [:show] do
    collection do
      post 'add_to_group'
      post 'remove_from_group'
      post 'mark_as_reviewed'
      get 'search'
    end
  end

  resources :activities do
    collection {
      get 'index'
      get 'show_all'
    }
  end

  resources :pages, param: :name do
    member {
      post 'preview'
    }
  end

  resources :watches, only: [:create, :destroy, :update]
  resources :watches do
    collection {
      delete 'delete_many'
    }
  end
  resources :ratings, only: [:create, :destroy, :update]

  resources :groups do
    collection {
      get 'show_all'
    }
  end
  resources :group_users
  
  resources :dericci_records
  resources :dericci_games do
    collection {
      get 'stats'
    }
  end
  resources :dericci_links do
    collection {
      delete 'delete_many'
      put 'update_many'
    }
  end
  resources :dericci_notes, only: [:index]
  resources :dericci_sales, only: [:index]

  resources :replies
  #resources :notifications, only: [:index, :show, :update, :destroy]
  resources :notifications do
    collection {
      get 'read_many'
      delete 'delete_many'
    }
  end

  get '/dla/schoenberg', to: 'catalog#legacy'
  get '/dla/schoenberg/:path', to: 'catalog#legacy'
  get '/dla/schoenberg/feeds/search.rss', to: 'catalog#legacy'
  
  get '/bookmarks/export', to: 'bookmarks#export', as: 'export_bookmarks'
  get '/bookmarks/reload', to: 'bookmarks#reload', as: 'reload_bookmarks'
  resources :bookmarks do
    collection {
      delete 'delete_all', to: 'bookmarks#destroy'
      get 'check'
    }
    member {
      get 'addtag'
      get 'removetag'
    }
  end

  resources :downloads do
    collection {
      get 'index', as: "downloads"
    }
    member {
      get 'show' 
      get 'delete', action: :destroy
    }
  end

  # it would be cleaner to have :entries here and merge
  # CatalogController into EntriesController, but that doesn't work,
  # because Rails won't be able to find the catalog view files from
  # the blacklight gem.
  blacklight_for :catalog
  get "/advanced/", to: 'advanced#index'

  resources :comments do
    collection {
      post 'mark_as_reviewed'
      get 'search'
    }
  end

  # these should probably be removed, no?
  get "/faq/", to: 'community#faq', as: 'faq'
  get "/about/", to: 'community#about', as: 'about'
  get "/technical_overview/", to: 'community#technical_overview', as: 'technical_overview'
  get "/project_history/", to: 'community#project_history', as: 'project_history'
  get "/user_agreement/", to: 'community#user_agreement', as: 'user_agreement'
  get '/community/', to: 'community#show', as: 'community'
  get '/community/stats', to: 'community#stats'

  get '/dashboard/contributions'
  get '/dashboard/activity'
  get '/dashboard/forum'

#  resources :delayed_jobs, only: [:index]

#  resources '/messages/', to: 'private_messages#index', as: 'private_messages'

  resources :private_messages do
  end

  # Note here that we point #show to BL's CatalogController
  resources :entries, except: [:show] do
    collection {
      post 'calculate_bounds'
      post 'mark_as_approved'
      post 'add_to_group'
      post 'remove_from_group'
      get 'types'
      get 'import'
      post 'upload'
    }
    member {
      patch '/revert_confirm/', to: 'entries#revert_confirm'
      patch '/revert/', to: 'entries#revert'
      post 'deprecate'
      post 'compose'
      get 'verify'
      get 'history'
      get 'similar'
      get 'manuscript_candidates'
    }
  end
  get '/entries/:id.json', to: 'entries#show_json', defaults: { format: 'json' }
  get '/entries/:id', to: 'catalog#show'
  #get '/feed' => 'entries#feed'

  resources :entry_dates do
    collection {
      get 'parse_observed_date'
    }
  end

  resources :entry_manuscripts do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      put 'update_multiple'
    }
  end

  get '/feedback/', to: 'feedback#index', as: 'feedback'
  post '/feedback/', to: 'feedback#send_email', as: 'send_feedback'
  get '/feedback/thanks', to: 'feedback#thanks', as: 'feedback_thanks'

  resources :languages do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'history'
      get 'merge'
      post 'merge'
      patch '/revert_confirm/', to: 'languages#revert_confirm'
      patch '/revert/', to: 'languages#revert'
    end
  end

  get '/linkingtool/entry/:id', to: 'linking_tool#by_entry', as: 'linking_tool_by_entry'
  get '/linkingtool/manuscript/:id', to: 'linking_tool#by_manuscript', as: 'linking_tool_by_manuscript'

  # helpful for debugging
  get '/login_as/:username', to: 'accounts#login_as', as: 'login_as'

  resources :manuscripts do
    collection do
      post 'mark_as_reviewed'
      get 'search'
    end
    member do
      get 'table'
      get 'citation'
      get 'entry_candidates'
      get 'manage_entries'
      get 'history'
      get 'edit', action: :show
    end
  end

  resources :names do
    collection do
      post 'mark_as_reviewed'
      get 'search'
      get 'suggest'
      get 'more_like_this'
      get 'problems'
    end
    member do
      patch '/revert_confirm/', to: 'names#revert_confirm'
      patch '/revert/', to: 'names#revert'
      get 'history'
      get 'merge'
      get 'timeline'
      post 'merge'
    end
  end

  resources :places do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'merge'
      post 'merge'
      get 'history'
      patch '/revert_confirm/', to: 'places#revert_confirm'
      patch '/revert/', to: 'places#revert'
    end
  end

  # use 'username' as identifier here for nicer URLs
  # 10-26-2017: have to specifically allow '.' character or else it gets used as the URL format
  get 'profiles/:username' => 'profiles#show', :constraints =>{:username =>/.*/}, :as => 'profile'
  
  resources :provenance do
    collection {
      get 'parse_observed_date'
    }
  end

  if !Rails.env.production?
    get '/raise_error/', to: 'debug#raise_error'
  end

  resources :sources do
    collection do
      post 'calculate_bounds'
      post 'mark_as_reviewed'
      get 'search'
      get 'similar'
      get 'conflict'
      get 'types'
    end
    member do
      get 'merge'
      post 'merge'
      get 'history'
      post 'update_status'
      patch '/revert/', to: 'sources#revert'
      patch '/revert_confirm/', to: 'sources#revert_confirm'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # matches unmatched path - needs to remain as LAST route
  
  match "*path", to: "errors#render_404", via: :all
end

rails_app/app/views/shared/_control_panel.html.erb
<div id="control-panel" class="collapse width in">
  <div class="scroll-box">
    <% if current_user %>
    <div class="panel panel-default">
        <div class="panel-heading" style="white-space: nowrap; padding-top: 10px; background: #4d6b98;">
            <div class="user-icon">
              <%= image_tag Thredded.avatar_url.call(current_user), class: 'img img-responsive dashboard-profile-picture' %>
            </div>
            <div class="user-info">
              <span class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown" style="color: white;">
                  <%= current_user.to_s %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="<%= main_app.profile_path(username: current_user.username) %>"><span class="glyphicon glyphicon-user"></span> My Profile</a></li>
                  <li><a href="<%= main_app.private_messages_path %>"><span class="glyphicon glyphicon-envelope"></span> My Messages</a></li>
                  <li><%= link_to main_app.edit_user_registration_path do %> <span class="glyphicon glyphicon-cog"></span> My Settings <% end %></li>
                  <% if current_user && !current_user.to_s.blank? %>
                    <li>
                      <%= link_to(main_app.destroy_user_session_path, :onclick => "localStorage.clear();") do %>
                        <span class="glyphicon glyphicon-log-out"></span> <%= t('blacklight.header_links.logout') %>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </span><br>
              <span class="text-muted" sdbm-tooltip="user_levels">User Level: <em><%= current_user.role %></em></span>
            </div>
        </div>
        <div class="panel-body">
          <ul class="nav">
            <%= render partial: "nav/notifications" %>
            <li>
              <a href="<%= main_app.dashboard_contributions_path %>"><span class="glyphicon glyphicon-dashboard"></span> Dashboard</a>
            </li>
            <li>
                <a href="/bookmarks"><span class="glyphicon glyphicon-bookmark"></span> Bookmarks</a>
            </li>
            <li>
                <a href="/downloads"><span class="glyphicon glyphicon-floppy-save"></span> Exports</a>
            </li>
            <li>
                <a href="/groups"><span class="glyphicon glyphicon-globe"></span> Groups</a>
            </li>          
            <li>
                <a href="/watches"><span class="glyphicon glyphicon-eye-open"></span> Watched Records</a>
            </li>
            <li class='dropdown'>
              <a href="" data-toggle="dropdown"><span class="glyphicon glyphicon-inbox"></span> Projects <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="/dericci_games"><span class="glyphicon glyphicon-tower"></span> De Ricci Name Game</a>
                </li>
                <li>
                  <a href="/dericci_records"><span class="glyphicon glyphicon-list"></span> De Ricci Archive</a>
                </li>
                <li>
                  <a href="/names/problems"><span class="glyphicon glyphicon-warning-sign"></span> Problem Names</a>
                </li>                
                <li>
                  <a href="/sparql-space"><span class="glyphicon glyphicon-certificate"></span> <b>SPARQL</b> Endpoint</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
    </div>

    <div class="control-panel-top">
      <div class="panel panel-default show-tools">
        <div class="panel-heading"><span class="h4">Tools</span></div>
        <div class="panel-body">
          <ul class="nav">
            <% if content_for? :add_entry %>
              <!--<li class="divider"></li>-->
              <%= yield :add_entry %>
            <% else %>
            <li class="dropdown">
              <a href="" data-toggle="dropdown"><span class="glyphicon glyphicon-plus"></span> Add New Entry <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="/entries/new">From a Source</a>
                </li>
                <li>
                  <%= link_to "Based on Personal Observation", main_app.new_source_path({create_entry: 1, source_type: 4}) %>
                </li>
              </ul>
            </li>
            <% end %>
            <%= yield :control_tools %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

    <% if !current_user %>
    <div class="panel panel-default" style="overflow: hidden;">
      <div class="panel-heading">
        <span class="h4">
          <span class="glyphicon glyphicon-log-in"></span> Login
        </span>
      </div>
      <div class="panel-body">
        <div style="padding: 0px 10px;">
          <%= render partial: 'devise/sessions/new', locals: {resource: User.new, resource_name: 'user', devise_mapping: Devise.mappings[:user]} %>      
        </div>
        <ul class="nav">
          <li>
            <%= link_to(new_registration_path('user')) do %>
              <span class="glyphicon glyphicon-log-in"></span> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to(new_password_path('user')) do %>
              <span class="glyphicon glyphicon-question-sign"></span> Forgot your password?
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <span class="h4">
          <span class="glyphicon glyphicon-link"></span>
          Related Links
        </span>
      </div>
      <div class="panel-body">
        <ul class="nav">
          <li class='dropdown'>
            <a href="" data-toggle="dropdown"><span class="glyphicon glyphicon-inbox"></span> Projects <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <a href="/dericci_games"><span class="glyphicon glyphicon-tower"></span> De Ricci Name Game</a>
              </li>
              <li>
                <a href="/dericci_records"><span class="glyphicon glyphicon-list"></span> De Ricci Archive</a>
              </li>
              <li>
                <a href="/names/problems"><span class="glyphicon glyphicon-warning-sign"></span> Problem Names</a>
              </li>
            </ul>
          </li>
          <li>
            <a href="https://schoenberginstitute.org/" title="The Schoenberg Institute for Manuscript Studies">
              <span class="glyphicon glyphicon-book"></span>
              The Schoenberg Institute for Manuscript Studies
            </a>
          </li>
          <li>
            <a href="http://dla.library.upenn.edu/dla/medren/search.html?fq=collection_facet%3A%22Lawrence%20J.%20Schoenberg%20Collection%22" title="Online digital facsimiles">
              <span class="glyphicon glyphicon-picture"></span>
              Penn in Hand
            </a>
          </li>
          <li>
            <a href="http://openn.library.upenn.edu/html/0001.html" title="Downloadable digital images and metadata">
              <span class="glyphicon glyphicon-picture"></span>
              OPenn
            </a>
          </li>
          <li>
            <a href="http://sceti.library.upenn.edu/ljscatalog/index.html" title="A printed catalog of early manuscripts">
              <span class="glyphicon glyphicon-folder-close"></span>
              Transformation of Knowledge
            </a>
          </li>
          <li>
            <a href="http://sceti.library.upenn.edu/legacy/" title="Online Exhibit">
              <span class="glyphicon glyphicon-education"></span>
              A Legacy Inscribed
            </a>
          </li>
          <li>
            <a href="https://mappingmanuscriptmigrations.org/en/" class="href">
              <span class="glyphicon glyphicon-map-marker"></span>
              Mapping Manuscript Migrations
            </a>
          </li>
        </ul>
      </div>
    </div>
    <% end %>
    <div class="img-brands">
      <a href="https://diggingintodata.org/" target="_blank"><%= image_tag 'logo_did.png', class: "img img-neh img-did" %></a>
      <a href="https://www.neh.gov/" target="_blank"><%= image_tag 'logo_neh.png', class: "img img-neh" %></a>
      <a href="https://www.transatlanticplatform.com/" target="_blank"><%= image_tag 'logo_tap.png', class: "img img-neh" %></a>
      <a href="https://www.imls.gov/" target="_blank"><%= image_tag 'logo_imls.png', class: "img img-neh" %></a>
    </div>
  </div>
</div>

rails_app/app/views/shared/_entry_name.html.erb
<%# This partial is for entry_ association records that contain a reference to a Name, an observed_name field, and certainty flags. this is the pattern for author, artist, and scribe %>
<% if record.author %><%= link_to record.author.name, name_path(record.author) -%><% if record.observed_name.present? %> (recorded as <%= record.observed_name %>)<%- end -%><%- else -%><%= record.observed_name %><%- end -%><% if record.role.present? %> (<%= record.role %>)<% end %><%= record.certainty_flags %>

rails_app/app/views/shared/_entry_scribe.html.erb
<% if entry_scribe.scribe %>
  <%= link_to entry_scribe.scribe.name, name_path(entry_scribe.scribe) %>
  <% if entry_scribe.observed_name.present? %>
    (recorded as <%= entry_scribe.observed_name %>)
  <% end %>
<% else %>
  <%= entry_scribe.observed_name %>
<% end %>
<%= entry_scribe.certainty_flags %>

rails_app/app/views/shared/_faq.html.erb
<div class="row">
    <div class=".col-sm-12" id="faq">
        <h1 class='text-info text-center'>
            Frequently Asked Questions
        </h1>
                
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">I have access to a source for manuscript data currently not included in the database. How do I add this content?</span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>You can enter the data yourself if you have an SDBM user account by selecting “Add New Entry” dropdown from the left sidebar, then selection either "From a Source" or "Based on Personal Observation"</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">Does the Schoenberg Database of Manuscripts (SDBM) own the manuscripts it describes?</span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>No, the SDBM does not own any manuscripts. We gather data about any manuscript produced before 1600 CE and composed of five or more folios, regardless of geographic location or institutional affiliation. We may at some point change the date and folio limits if the user community believes this is the right course of action. Let us know what you think!</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">Why does the data seem so messy?</span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>Larry Schoenberg created his personal database as an Excel file in 1997, then created an Access database as the spreadsheet grew and he added more fields. These early formats required character limits, thus frequently forcing him to abbreviate data. As he began sharing his spreadsheet with friends, the user base and scope of the project grew. In 2009, data standards were created and refined and fields were added with the intention of improving information quality. It has been and remains impossible for SDBM staff to go back through all early entries to update the data to current standards. We provide warning labels on those entries that were created prior to the development of the New SDBM.

                        Also, people just make mistakes sometimes. You can help us improve data quality by commenting on entries and adding Personal Observations to the database.</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">I disagree with the data provided in an entry. How do I change it?</span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>There are many ways to help us improve data. While you can never edit another user’s entry, we do encourage you to create a Personal Observation if you have knowledge of a manuscript that is different from data recorded in an entry. If you notice an error in the way that data may have been transcribed from a source, you can leave a comment at the bottom of the description to notify us of the problem. You can also email us at sdbm@pobox.upenn.edu if you prefer to keep your comments private, though you will miss out on potential conversations with other users. Keep in mind that the SDBM aims to reproduce data exactly as it is given in the a source (e.g. an auction catalogue).</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">Some entries are linked together but there is no way they can be the same manuscript, in my informed opinion. Why is that?</span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>Again, people make mistakes. Help us fix them by editing the links or notifying us.</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">I am looking at a Manuscript Record in which all of the linked entries contain exactly the same data across fields. How can this be, since, for example, one source catalog dates to the 16th-century, before the metric system had been invented, and yet an entry associated with this catalog gives dimensions in millimeters?
            </span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>At one point in the history of the SDBM, it was determined that all linked entries should contain the same data. We no longer do this because there is no way to determine which source has the “right” data. If you find an instance of this, please help us fix it!</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">Why can’t I find a particular major sale or a collection catalogue? Why is it not represented in the database?
            </span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>It is entirely possible that a sale of great significance has not been entered because we have not had access to a catalog. Up until the New SDBM was created, we have relied on a handful of researchers limited to certain locations. This is why we decided to open it up to the user-community.</p>
                        <p>It may also be that the catalog has been entered in such a way as to make it difficult to locate within the database. If you are having trouble finding something, email us at sdbm@pobox.upenn.edu.</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">Why are there no images?
            </span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>We do not include images of manuscripts because we do not own the manuscripts, nor do we include images of sources and other evidence because this allows us to keep the data light and ensure sustainability. The user has the option to add URLs in Entries that point to images of the manuscript described or other source evidence.</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">Whom do I contact to get a reproduction of a manuscript described in the database?
            </span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>Unfortunately, we can’t help you out with this (see the previous question). If an Entry or a Manuscript Record includes current location data, contact the institution described there. If no current location information exists, try using data recorded in the provenance history to track its current location.</p>
                    </div>
                </div>
            </div>
        </div>
         
        <div class="panel panel-default">
            <div class="panel-heading"><span class="h4">Finally, why do many fields (e.g., Seller, Buyer, Author, Place, Language, Provenance Agent, etc.) have an “As Recorded” subfield and a “Find in Name Authority” subfield ?</span></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <p>The “As recorded” field allows you to enter a name exactly as it is recorded in your source, and allows us to capture variations in the way a name is recorded across multiple sources. The authority field is there to link the record to a Name, Place, or Language Authority List maintained by the SDBM staff. It is our goal to make our Authority Lists linkable to other authorities such as the Virtual International Authority File (VIAF). For more information on VIAF, go to <a href="http://viaf.org/">http://viaf.org/</a>.</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

rails_app/app/views/shared/_language.html.erb
<% if entry_language.language %>
  <%= link_to entry_language.language.name, language_path(entry_language.language) -%>
  <% if entry_language.observed_name.present? %>
    (recorded as <%= entry_language.observed_name %>)
  <% end %>
<% else %>
  <%= entry_language.observed_name %>
<% end %>
<%= entry_language.certainty_flags %>

rails_app/app/views/shared/_modal.html.erb
<%# HTML to be used with SDBM.showModal() %>
<div class="modal fade" id="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">&nbsp;</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

rails_app/app/views/shared/_my_bookmarks.html.erb
<% if current_user %>
  <div class="panel panel-default dl-inline" id="my_bookmarks">
      <ul class="nav nav-tabs">
        <li ng-repeat="(name, bookmarks) in all_bookmarks" class="bookmark-nav-button" ng-class="{active: (name == active) }">
          <a ng-click="addTabToStorage(name);">{{ name }}
          <span class="badge">{{ (bookmarks | filter:hasTag).length }}</span></a>
        </li>
      </ul>
    <div class="tab-content bookmark-panes">
      <div ng-repeat="(name, bookmarks) in all_bookmarks" class="tab-pane fade" id="bookmark-tab-{{ name }}" ng-class="{active: (name == active), in: (name == active)}">
        <ul class="list-group bookmarks">
          <li class="list-group-item text-center" ng-if="search_tag.length > 0 && (bookmarks | filter:hasTag).length <= 0">
            <b class="text-primary">SEARCH: {{ search_tag }}</b> ... no results ...<br>
            <a class='' ng-click="searchTag('')">Clear Search <span class="glyphicon glyphicon-remove"></span></a>
          </li>
          <li class="list-group-item" ng-if="bookmarks.length <= 0">
            No records of this type have been bookmarked yet.
          </li>
          <li class="list-group-item" ng-repeat="bookmark in bookmarks | filter:hasTag">
              <dl class="document-show-heading dl-invert" style="padding-left: 10px;">
                  <dt class='h4'>
                    <strong><a href="{{ bookmark.link }}"> {{ bookmark.public_id }}</a></strong>
                    <span ng-bind-html="actionButton(bookmark)"></span> 
                    <a href="" class='remove-bookmark control-bookmark pull-right' ng-click="removeBookmark(name, bookmark)">
                      <span class="glyphicon glyphicon-remove"></span>
                    </a>
                  </dt>
              </dl>
              <dl class="document-metadata dl-invert dl-horizontal">
                <dt ng-repeat-start="(key, value) in bookmark.details track by $index">{{ key }}</dt>
                <dd ng-repeat-end>{{ value }}</dd>
                <dt>
                  Tags
                </dt>
                <dd>
                  <ul class="list-inline">
                    <li ng-if="bookmark.tags.length <= 0" class='text-warning'>This bookmark has no tags.</li>
                    <li ng-repeat="tag in bookmark.tags" class="bookmark-tag" ng-class="{'btn-info btn-lg' : tag == search_tag, 'bg-primary' : tag != search_tag}">
                        <a href="" ng-click="searchTag(tag);">{{ tag }}</a>
                        <a href="" class='remove-bookmark-tag-confirm small' ng-click="removetag(bookmark, tag)"><span class="glyphicon glyphicon-remove"></span></a>
                    </li>
                  </ul>
                </dd>
                <a ng-show="!bookmark.showAddTag" href="" class="btn btn-sm btn-success" ng-click="bookmark.showAddTag = !bookmark.showAddTag">Add Tag <span class="glyphicon glyphicon-tag"></span></a>
                <div class="form-inline">
                  <div class="input-group add-bookmark-tag" ng-show="bookmark.showAddTag">
                    <input type='text' class='form-control' placeholder="add tag..." ng-model="bookmark.newtag" ng-keyup="$event.keyCode == 13 && addtag(bookmark, bookmark.newtag)">
                    <a href="" class="input-group-addon add-bookmark-tag-confirm" ng-click="addtag(bookmark, bookmark.newtag)"><span class="glyphicon glyphicon-plus"></span></a>
                    <a href="" class="input-group-addon add-bookmark-tag-confirm" ng-click="bookmark.showAddTag = !bookmark.showAddTag">Cancel</a>
                  </div>
                </div> 
              </dl>
          </li>
        </ul>
      </div>
  
    </div>
    <div class="form-inline clearfix navbar-form">
      <div class="input-group">
        <input type="text" class="form-control" name="tag-search" placeholder="Filter By Tag..." size=12 ng-model="tagSearch" ng-keyup="$event.keyCode == 13 && searchTag(tagSearch)">
        <a href="" class="input-group-addon" ng-click="searchTag('')"><span>Clear</span></a>
      </div>
      <a href='/bookmarks' class="pull-right text-right text-invert">Manage<br>Bookmarks</a>
    </div>
  </div>
<% end %>

rails_app/app/views/shared/_navbar_brand.html.erb
<%= link_to(main_app.root_path, class: "navbar-brand") do %>
  <span class="word">
    <span class="first-letter">S</span>choenberg
  </span>
  <span class="word">
    <span class="first-letter">D</span>ata<span class="first-letter">b</span>ase
  </span>
  <span class="word">of</span>
  <span class="word"><span class="first-letter">M</span>anuscripts</span>
<% end %>

rails_app/app/views/shared/_place.html.erb
<% if entry_place.place %>
  <%= link_to entry_place.display_value, place_path(entry_place.place) -%>
<% else %>
  <%= entry_place.display_value %>
<% end %>
<%= entry_place.certainty_flags %>