rails_app/config/routes.rb
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'

  get "/sparql-space", :to => "sparql#index"
  
  root :to => "catalog#index"

  resources :accounts, except: [:show] do
    collection do
      post 'add_to_group'
      post 'remove_from_group'
      post 'mark_as_reviewed'
      get 'search'
    end
  end

  resources :activities do
    collection {
      get 'index'
      get 'show_all'
    }
  end

  resources :pages, param: :name do
    member {
      post 'preview'
    }
  end

  resources :watches, only: [:create, :destroy, :update]
  resources :watches do
    collection {
      delete 'delete_many'
    }
  end
  resources :ratings, only: [:create, :destroy, :update]

  resources :groups do
    collection {
      get 'show_all'
    }
  end
  resources :group_users
  
  resources :dericci_records
  resources :dericci_games do
    collection {
      get 'stats'
    }
  end
  resources :dericci_links do
    collection {
      delete 'delete_many'
      put 'update_many'
    }
  end
  resources :dericci_notes, only: [:index]
  resources :dericci_sales, only: [:index]

  resources :replies
  #resources :notifications, only: [:index, :show, :update, :destroy]
  resources :notifications do
    collection {
      get 'read_many'
      delete 'delete_many'
    }
  end

  get '/dla/schoenberg', to: 'catalog#legacy'
  get '/dla/schoenberg/:path', to: 'catalog#legacy'
  get '/dla/schoenberg/feeds/search.rss', to: 'catalog#legacy'
  
  get '/bookmarks/export', to: 'bookmarks#export', as: 'export_bookmarks'
  get '/bookmarks/reload', to: 'bookmarks#reload', as: 'reload_bookmarks'
  resources :bookmarks do
    collection {
      delete 'delete_all', to: 'bookmarks#destroy'
      get 'check'
    }
    member {
      get 'addtag'
      get 'removetag'
    }
  end

  resources :downloads do
    collection {
      get 'index', as: "downloads"
    }
    member {
      get 'show' 
      get 'delete', action: :destroy
    }
  end

  # it would be cleaner to have :entries here and merge
  # CatalogController into EntriesController, but that doesn't work,
  # because Rails won't be able to find the catalog view files from
  # the blacklight gem.
  blacklight_for :catalog
  get "/advanced/", to: 'advanced#index'

  resources :comments do
    collection {
      post 'mark_as_reviewed'
      get 'search'
    }
  end

  # these should probably be removed, no?
  get "/faq/", to: 'community#faq', as: 'faq'
  get "/about/", to: 'community#about', as: 'about'
  get "/technical_overview/", to: 'community#technical_overview', as: 'technical_overview'
  get "/project_history/", to: 'community#project_history', as: 'project_history'
  get "/user_agreement/", to: 'community#user_agreement', as: 'user_agreement'
  get '/community/', to: 'community#show', as: 'community'
  get '/community/stats', to: 'community#stats'

  get '/dashboard/contributions'
  get '/dashboard/activity'
  get '/dashboard/forum'

#  resources :delayed_jobs, only: [:index]

#  resources '/messages/', to: 'private_messages#index', as: 'private_messages'

  resources :private_messages do
  end

  # Note here that we point #show to BL's CatalogController
  resources :entries, except: [:show] do
    collection {
      post 'calculate_bounds'
      post 'mark_as_approved'
      post 'add_to_group'
      post 'remove_from_group'
      get 'types'
      get 'import'
      post 'upload'
    }
    member {
      patch '/revert_confirm/', to: 'entries#revert_confirm'
      patch '/revert/', to: 'entries#revert'
      post 'deprecate'
      post 'compose'
      get 'verify'
      get 'history'
      get 'similar'
      get 'manuscript_candidates'
    }
  end
  get '/entries/:id.json', to: 'entries#show_json', defaults: { format: 'json' }
  get '/entries/:id', to: 'catalog#show'
  #get '/feed' => 'entries#feed'

  resources :entry_dates do
    collection {
      get 'parse_observed_date'
    }
  end

  resources :entry_manuscripts do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      put 'update_multiple'
    }
  end

  get '/feedback/', to: 'feedback#index', as: 'feedback'
  post '/feedback/', to: 'feedback#send_email', as: 'send_feedback'
  get '/feedback/thanks', to: 'feedback#thanks', as: 'feedback_thanks'

  resources :languages do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'history'
      get 'merge'
      post 'merge'
      patch '/revert_confirm/', to: 'languages#revert_confirm'
      patch '/revert/', to: 'languages#revert'
    end
  end

  get '/linkingtool/entry/:id', to: 'linking_tool#by_entry', as: 'linking_tool_by_entry'
  get '/linkingtool/manuscript/:id', to: 'linking_tool#by_manuscript', as: 'linking_tool_by_manuscript'

  # helpful for debugging
  get '/login_as/:username', to: 'accounts#login_as', as: 'login_as'

  resources :manuscripts do
    collection do
      post 'mark_as_reviewed'
      get 'search'
    end
    member do
      get 'table'
      get 'citation'
      get 'entry_candidates'
      get 'manage_entries'
      get 'history'
      get 'edit', action: :show
    end
  end

  resources :names do
    collection do
      post 'mark_as_reviewed'
      get 'search'
      get 'suggest'
      get 'more_like_this'
      get 'problems'
    end
    member do
      patch '/revert_confirm/', to: 'names#revert_confirm'
      patch '/revert/', to: 'names#revert'
      get 'history'
      get 'merge'
      get 'timeline'
      post 'merge'
    end
  end

  resources :places do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'merge'
      post 'merge'
      get 'history'
      patch '/revert_confirm/', to: 'places#revert_confirm'
      patch '/revert/', to: 'places#revert'
    end
  end

  # use 'username' as identifier here for nicer URLs
  # 10-26-2017: have to specifically allow '.' character or else it gets used as the URL format
  get 'profiles/:username' => 'profiles#show', :constraints =>{:username =>/.*/}, :as => 'profile'
  
  resources :provenance do
    collection {
      get 'parse_observed_date'
    }
  end

  if !Rails.env.production?
    get '/raise_error/', to: 'debug#raise_error'
  end

  resources :sources do
    collection do
      post 'calculate_bounds'
      post 'mark_as_reviewed'
      get 'search'
      get 'similar'
      get 'conflict'
      get 'types'
    end
    member do
      get 'merge'
      post 'merge'
      get 'history'
      post 'update_status'
      patch '/revert/', to: 'sources#revert'
      patch '/revert_confirm/', to: 'sources#revert_confirm'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # matches unmatched path - needs to remain as LAST route
  
  match "*path", to: "errors#render_404", via: :all
end

rails_app/app/controllers/entries_controller.rb
# Manage Entries screen is much more complicated than other screens
# that subclass from ManageModelsController, but we use it anyway
# for consistency.
#
# Note: CSV Export from Manage Entries page makes use of Blacklight
# search; see CatalogControllerConfiguration to see how search results
# are rendered in CSV format.
class EntriesController < SearchableAuthorityController

  # include Blacklight modules so that we get the same search
  # functionality as in CatalogController, except that in this
  # controller, we customize a few things about how search works.

  include Blacklight::Catalog

  include CatalogControllerConfiguration

  include Revert

  # the blacklight_advanced_search gem includes this automatically in
  # CatalogController but not here, so we include it explicitly
  include BlacklightAdvancedSearch::Controller
  
  include LogActivity

  before_action :set_entry, only: [:show, :show_json, :edit, :update, :destroy, :similar, :history, :deprecate, :verify, :personal_observation]
  include AddToGroup

  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy, :similar, :mark_as_approved, :deprecate, :import, :upload]

  respond_to :html, :json

  load_and_authorize_resource :only => [:index, :edit, :update, :destroy, :mark_as_approved, :deprecate, :import, :upload]

  def import
  end

  def upload
    errors = []
    check = params[:check]
    params["entries"].to_a.each do |param|
      filter = entry_params_for_create_and_edit(param)
      filter[:draft] = false # making sure 'draft' is understood properly by public catalog view...

      #puts filter[:source_id]
      # option: use valid? to check all entries without saving, so the user can check validations without huge overhead FIRST
      # 
      # i.e. have params 'check' to determine whether it is SAVING or CHECKING, require 'check' first...
      # 
      # e = Entry.create(filter)
      if check
        e = Entry.new(filter)
        e.valid?
      else
        e = Entry.new(filter)
        e.save_by(current_user)
      end

      if e.errors.count > 0
        errors.push(e.errors.messages)
      else
        errors.push(nil)
      end
    end

    respond_to do |format|
      format.js {
        if errors.count > 0
          render json: {errors: errors}
        else
          render json: {message: "Sucess", succes: true}
        end      
      }    
    end
  end

  def model_class
    Entry
  end

  def format_search(s)
    ids = s.results.map(&:id)
    # cinludes bookmarks/watches??
    results = Entry.with_associations.includes(:bookmarks, :watches).where(id: ids).order(ids.count > 0 ? "FIELD(id, #{ids.join(', ')})" : "id desc").map { |e| 
      e.as_flat_hash.merge({ 
        can_edit: can?(:edit, e), 
        bookmarkwatch: (render_to_string partial: "nav/bookmark_watch_table", locals: {model: e }, layout: false, formats: [:html]) 
      }) 
    }
    respond_to do |format|
      format.json {
        render json: {
                 limit: s.results.count,
                 offset: s.results.offset,
                 total: s.total,
                 results: results,
               }
      }
      format.csv {
        make_csv(results, @d)
      }
    end
  end

  def index
    @search_fields = model_class.search_fields
    @fields = model_class.fields
    @filters = model_class.filters
    @dates = model_class.dates

    @bookmarks = current_user.bookmarks
    # need to... get the fields configured for blacklight, 

    @filter_options = ["with", "without", "blank", "not blank", "less than", "greater than"]
    @field_options = ["contains", "does not contain", "blank", "not blank"]
    @date_options = ["before", "after", "near", "exact"]    

    params.merge!("role" => current_user.role)
    #if current_user.role != "admin"
    #  params.merge!("draft" => ["false"], "draft_option" => ["with"])
    #end

    # Dates are treated as strings, so need a bit of manipulating
    [:source_date, :source_date_search, :sale_date].each do |date_key|
      if params[date_key]
        params[date_key] = Array(params[date_key])
        params[date_key].map! do | date |
          date.gsub('-', '').gsub('/', '').ljust(8, "*")
        end
      end
    end

    if params[:format] == 'csv'
      if current_user.downloads.count >= 5
        render json: {error: 'at limit'}
        return
      end   
      @d = Download.create({filename: "#{search_model_class.to_s.downcase.pluralize}.csv", user_id: current_user.id})

      Entry.delay.do_csv_search(params, @d)
#      EntriesController.delay.do_csv_search(params, search_params_logic, @d)

      respond_to do |format|
        format.csv {
          render json: {id: @d.id, filename: @d.filename, count: current_user.downloads.count} 
        }
      end
    elsif params[:format] == 'json'
      s = Entry.do_search(params)
      format_search s      
    end
  end

  def feed
    @page_title = "RSS Feed"
    @entries = Entry.last(100).reverse
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  # JSON data structure optimized for editing page. This weird action
  # exists because we want CatalogController to handle #show, but we
  # want to format the JSON differently from how it does it.
  def show_json
    respond_to do |format|
      format.json { render "show.json" }
    end
  end

  # Overrides Blacklight::Catalog#render_search_results_as_json to
  # provide search results in JSON format expected by datatables
  # widget, which is the only thing that uses (or should use) this,
  # since we return arrays instead of objects with more meaningful
  # keys.

  def render_search_results_as_json
    retval = {
      draw: params[:draw],
    }
    begin
      pinfo = pagination_info(@response)

      data = @document_list.map do |doc|
        entry = doc.model_object
        # have to add can_edit here, since this is where current_user is accessible
        !entry.nil? ? entry.as_flat_hash.merge({
          can_edit: can?(:edit, entry), 
          bookmarkwatch: (render_to_string partial: "nav/bookmark_watch_table", locals: {model: entry }, layout: false, formats: [:html]),
        }) : {}
      end

      retval.merge!({
                      recordsTotal: pinfo[:total_count],
                      recordsFiltered: pinfo[:total_count],
                      data: data,
                    })
    rescue Exception => e
      puts e.backtrace
      retval.merge!({
                      error: e.to_s
                    })
    end
    retval
  end

  # Overrides Blacklight::Catalog::SearchContext#add_to_search_history
  def add_to_search_history search
    # this is a noop: prevent this controller's searches from being
    # saved, because that's confusing to end users.
  end

  def new
    @entry = Entry.new
    @source_id = params[:source_id]
=begin    
    if @source_id.present?
      respond_to do |format|
        format.html { render "edit" }
      end
    else
      respond_to do |format|
        format.html { render "select_source" }
      end
    end
=end
    respond_to do |format|
      format.html { render "edit" }
    end
  end

  # creating composite provenance
  def compose
    s = Source.new({date: Date.today.strftime("%Y-%m-%d"), title: "Provenance Observation (#{current_user.username}): SDBM_MS_#{params[:manuscript_id]}", author: current_user.username, source_type: SourceType.find(8), created_by: current_user, status: Source::TYPE_STATUS_ENTERED})
    s.save!
    params[:source_id] = s.id
    create
  end

  def create
    success = false
    ActiveRecord::Base.transaction do
      filtered = entry_params_for_create_and_edit(params)
      @entry = Entry.new(filtered)
      @entry.created_by_id = current_user.id
      @entry.source_id = params[:source_id]
      success = @entry.save

      if success
        if params[:new_comment].present?
          c = Comment.new(
            comment: params[:new_comment],
            created_by_id: current_user.id,
            #commentable_id: @entry.id,
            #commentable_type: "Entry"
            #entry_comments_attributes: [
            #  {
            #    entry_id: @entry.id,
            #  }
            #]
            )
          c.save!
        end
        # link to manuscript
        if params[:manuscript_id].present?
          em = EntryManuscript.new(
            entry_id: @entry.id,
            manuscript_id: params[:manuscript_id],
            relation_type: EntryManuscript::TYPE_RELATION_IS
          )
          if em.save
            flash.now[:success] = "Your observation has been automatically linked to SDBM_MS_#{params[:manuscript_id]}"
          end
        elsif params[:new_manuscript].present? && params[:original_entry]
          m = Manuscript.create!
          em = EntryManuscript.new(
            entry_id: @entry.id,
            manuscript_id: m.id,
            relation_type: EntryManuscript::TYPE_RELATION_IS
          )
          em2 = EntryManuscript.new(
            entry_id: params[:original_entry],
            manuscript_id: m.id,
            relation_type: EntryManuscript::TYPE_RELATION_IS
          )
          if em.save && em2.save
            flash.now[:success] = "Your observation has been automatically linked to #{m.public_id}"
          end
        end

        # auto-watch record, if appropriate setting is set
        if current_user.notification_setting.auto_watch
          Watch.create(watched: @entry, user: current_user)
        end

        @transaction_id = PaperTrail.transaction_id
      end
    end
    respond_to do |format|
      format.json {
        if success
          render "show"
        else
          json_response = { errors: @entry.errors.messages }
          render json: json_response, status: :unprocessable_entity
        end
      }
      format.html {
        redirect_to edit_entry_path(@entry)
      }
    end
  end

  def edit
    expires_now
  end

  def update
    success = false
    errors = nil

rails_app/app/views/entries/_edit_buttons.html.erb
<div class="row" style="padding-bottom: 20px;" ng-show="!entry.deprecated">
    <div class="col-sm-4">
        <button class="btn btn-primary save-button" ng-click="save(false)" ng-disabled="entryForm.$invalid || currentlySaving || !entry.source">Save</button>
        <button ng-if="entry.draft || (!entry.id && !sdbmutil.getManuscriptId() && !sdbmutil.getNewManuscript())" ng-click="saveAsDraft()" class="btn btn-default save-button" ng-disabled="entryForm.$invalid || currentlySaving || !entry.source || (!entry.draft && num_drafts >= 10)" title="You may save up to 10 drafts at a time." >Save as Draft</button>
        <a class="btn btn-warning" id='cancelEdit' href="{{ entry.id ? '/entries/' + entry.id : '/dashboard'}}">Cancel</a>
    </div>
    <div class="col-sm-8 text-right">
        <span ng-if="entry && draft" >
            <span class="text-info">An unsaved version from <b>{{ draft.updated_object.toLocaleDateString() }}</b>, <b>{{ draft.updated_object.toLocaleTimeString() }}</b> has been detected </span>
            <a href="" class="btn btn-default" ng-click="loadDraft()">
                <span class="glyphicon glyphicon-repeat"></span>
                Restore
            </a>            
        </span>
        <a href="" data-toggle="modal" data-target="#backupSettings" class="btn btn-default" ng-if="entry.id || entry.source">
            <span class="glyphicon glyphicon-refresh"></span> Auto-backup {{ backup == 'enabled' ? 'enabled' : 'disabled' }}
        </a>
    </div>
    <div class="col-sm-12 label-alignment" ng-show="entryForm.$invalid">
        <div style="color: red;">
            You must correct the form inputs highlighted in red before you can save this form.
        </div>
    </div>
</div>

<div class="modal fade" id="backupSettings">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <span class="h3">Would you like the SDBM to auto-backup your work?</span>
                <a href="#backupSettings" id="dismiss-welcome" data-dismiss="modal" data-target="#backupSettings" class='pull-right' style="color: #333;"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
            <div class="modal-body">
                <p>The SDBM allows you to auto-backup your work by saving in progress data in the browser's local storage.  In the event that your page is closed without saving, you may be able to recover your work.  However, you may also opt-out of this feature if you desire.</p>
                <table class="table table-responsive">
                    <tbody>
                        <tr>
                            <td>
                                <input type="radio" class="form-control" value="enabled" ng-model="backup">
                            </td>
                            <td style="vertical-align: middle;">
                                Always enabled
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="radio" class="form-control" value="temporarily_disabled" ng-model="backup">
                            </td>
                            <td style="vertical-align: middle;">
                                Disable for current session
                            </td>
                        </tr>
                        <tr class='table-danger'>
                            <td>
                                <input type="radio" class="form-control" value="disabled" ng-model="backup">
                            </td>
                            <td style="vertical-align: middle;">
                                Always disabled
                            </td>
                        </tr>
                        <tr>
                            <td colSpan="2"><input type="submit" class="form-control text-center" value="Confirm" ng-click="setBackup()" data-dismiss="modal" data-target="#backupSettings" href="#backupSettings"></input></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

rails_app/app/views/entries/_index_extra.html.erb
<%= render :partial => 'shared/deprecate_entry_modal' %>

rails_app/app/views/entries/_preview.html.erb
<% entry = record %>
    <% if entry.nil? %>
    <p>Error: couldn't retrieve model object from database.</p>
    <% else %>
    <div class="panel-heading">
        <strong class="h4"><%= link_to entry.public_id, entry_path(entry) %></strong>
        <% if !entry.approved %>
              <span class="text-warning"><span class="glyphicon glyphicon-alert"></span> Unapproved</span>
        <% end %>
        <% if entry.draft && can?(:edit, entry) %>
          <%= link_to(entry_path(entry.id, draft: false, cumulative_updated_at: entry.cumulative_updated_at), :method => :patch, :title => "Publish Draft", :class => "btn btn-sm btn-default pull-right publish-btn", :data => {:confirm => "Are you sure you wish to publish this entry?  It will become publicly viewable from this point forward."}) do %>
            <span class="glyphicon glyphicon-file"></span>
          <% end %>
          <%= link_to entry_path(entry), :format => :html, :method => :delete, :title => "Delete Draft", :class => "btn btn-sm btn-default pull-right delete-draft-btn", :data => {:confirm => "Are you sure you wish to delete this entry?  All data entered will be lost permanently."} do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        <% end %>
    </div>
    <div class="panel-body">
    <dl class="document-metadata">
        <% manuscripts_str = render partial: "shared/entry_manuscripts", locals: { entry: entry } %>
        <% if manuscripts_str.present? %>
        <dt></dt>
        <dd>
            <%= manuscripts_str %>
        </dd>
        <% end %>

      <dt>Source</dt>
      <dd>
          <%= link_to entry.source.display_value, source_path(entry.source) %> (<%= entry.source.source_type.display_name %>)
      </dd>

        <% if entry.catalog_or_lot_number.present? %>
      <dt>Cat./Lot #</dt>
      <dd><%= entry.catalog_or_lot_number %></dd>
        <% end %>

        <% if entry.institution.present? %>
      <dt>Institution/Collection</dt>
      <dd><%= entry.institution %></dd>
        <% end %>
        
        <% if (sale = entry.get_sale).present? %>

          <% if (selling_agents = sale.get_selling_agents).present? %>
              <dt>Selling Agent(s)</dt>
              <dd>
                  <% selling_agents.each do |selling_agent| %>
                    <% if selling_agent.agent %>
                      <a href="<%= name_path(selling_agent.agent) %>"><%= selling_agent.agent.name %></a><br>
                    <% else %>
                      <%= selling_agent.observed_name %><br>
                    <% end %>
                  <% end %>
              </dd>
          <% end %>

          <% if (sellers_or_holders = sale.get_sellers_or_holders).present? %>
              <dt>Seller(s)</dt>
              <dd>
                  <% sellers_or_holders.each do |seller_or_holder| %>
                    <% if seller_or_holder.agent %>
                      <a href="<%= name_path(seller_or_holder.agent) %>"><%= seller_or_holder.agent.name %></a><br>
                    <% else %>
                      <%= seller_or_holder.observed_name %><br>
                    <% end %>
                  <% end %>
              </dd>
          <% end %>

          <% if (buyers = sale.get_buyers).present? %>
              <dt>Buyer(s)</dt>
              <dd class="col-sm-10">
                  <% buyers.each do |buyer| %>
                    <% if buyer.agent %>
                      <a href="<%= name_path(buyer.agent) %>"><%= buyer.agent.name %></a><br>
                    <% else %>
                      <%= buyer.observed_name %><br>
                    <% end %>
                  <% end %>
              </dd>
          <% end %>

        <% end %>

        <% if entry.entry_titles.length > 0 %>
      <dt>Titles</dt>
        <dd>
        <% entry.entry_titles.each do |entry_title| %>
          <%= entry_title.title %> <% if entry_title.common_title.present? %>[<%= entry_title.common_title %>]<% end %><br/>
        <% end %>
        </dd>
        <% end %>

        <% if entry.entry_authors.length > 0 %>
        <dt>Authors</dt>
        <dd>
        <% entry.entry_authors.each do |entry_author| %>
          <% if entry_author.observed_name.present? %>
            <%= entry_author.observed_name %>
            <% if entry_author.role %>(<%= entry_author.role %>)<% end %>
            <% if entry_author.author %>
            (<%= link_to entry_author.author.name, name_path(entry_author.author) %>)
            <% end %>
          <% elsif entry_author.author %>
            <%= link_to entry_author.author.name, name_path(entry_author.author) %>
            <% if entry_author.role %>(<%= entry_author.role %>)<% end %>
          <% end %>
          <br/>
        <% end %>
        </dd>
        <% end %>

        <% if entry.entry_dates.length > 0 %>
        <dt>Dates</dt>
        <dd>
        <% entry.entry_dates.each do |entry_date| %>
          <%= entry_date.display_value %><br/>
        <% end %>
        </dd>
        <% end %>

        <% if entry.entry_places.length > 0 %>
        <dt>Places</dt>
        <dd>
        <% entry.entry_places.each do |entry_place| %>
          <%= entry_place.display_value %><br/>
        <% end %>
        </dd>
        <% end %>

        <% if entry.folios.present? %>
        <dt>Folios</dt>
        <dd>
            <%= entry.folios %>
        </dd>
        <% end %>

        <% if (provenance_count = entry.provenance.length) > 0 %>
        <dt>Provenance Info</dt>
        <dd>
            This entry has <%= provenance_count %> provenance records involving: 
            <% entry.unique_provenance_agents.each do |unique_provenance_agent| %>
                <% if unique_provenance_agent[:agent].present? %>
                <a href="<%= url_for unique_provenance_agent[:agent] %>"><%= unique_provenance_agent[:agent] %></a>
                <% else %>
                  <%= unique_provenance_agent[:name] %>
                <% end %>
            <% end %>
        </dd>
        <% end %>
    </dl>
    <div class="text-center text-muted">
      <span class="glyphicon glyphicon-time"></span> Added On <%= entry.created_at.to_formatted_s(:long) %>
    </div>
    </div>
    <% end %>

rails_app/app/views/entries/_sub_history.html.erb
 
    <% if sublist %>
    <% sublist.each_with_index do |ul, index| %>
        <% if ul.count > 0 %>
        <div class="row">
            <div class="col-sm-12">
                <div id="myCarousel<%= ul[0].item_type %><%= index %>" class="carousel slide"><!-- data-interval='false' data-wrap='false'>-->
                          <div class="carousel-inner" role="listbox">
                            <% ul.reverse.each do |version| %>
                                <% formatter = EntryVersionFormatter.new(version) %>
                                <% if formatter.simple_details.count > 0 %>
                                    <div class="item <%= version == ul.first ? 'active' : '' %> <%= version.event == 'destroy' ? 'bg-danger' : ( version.event == 'create' ? 'bg-success' : 'bg-info') %>">
                                        <% muted = (version.event == 'create' && !version.item) || (version.event == 'destroy' && version.item) %> 
                                        <div class='row <%= muted ? "text-muted" : "" %>'>
                                            <div class="col-sm-2 text-right"><%= version.created_at.to_formatted_s(:long) %></div>
                                            <div class="col-sm-1">
                                                <% if User.exists? version.whodunnit %>
                                                    <%= User.find(version.whodunnit) %>
                                                <% else %>
                                                    <span class="text-muted">Unknown</span>
                                                <% end %>
                                            </div>
                                            <div class='col-sm-2'><span class=""><%= formatter.action %></span></div>
                                            <div class='col-sm-5'>
                                                <% formatter.simple_details.each do |detail| %>
                                                    <%= sanitize simple_format(detail), tags: %w(b) %><br>
                                                <% end %>
                                            </div>
                                            <div class='col-sm-2 text-left'>
                                                <% if can? :edit, @entry %>
                                                    <%= link_to "Undo", revert_confirm_entry_path(@entry, :version_id => [version.id]), :method => 'patch', class: "btn-undo btn btn-default #{muted ? 'disabled' : ''}", disabled: muted %>
                                                <% end %>
                                            </div>
                                        </div>
                                    </div>
                                <% end %>
                            <% end %>
                          </div>                  

                      <!-- Left and right controls -->
                      <a class="left carousel-control" href="#myCarousel<%= ul[0].item_type %><%= index %>" role="button"><!-- data-slide="prev">-->
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="right carousel-control" href="#myCarousel<%= ul[0].item_type %><%= index %>" role="button"><!-- data-slide="next">-->
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                </div>
            </div>
        </div>
        <% end %>
    <% end %>
    <% end %>

rails_app/app/views/entries/manuscript_already_exists.html.erb
<h1>Oops!</h1>

<p>You are trying to reach the page to find or create a manuscript,
but <a href="<%= edit_entry_path(@entry) %>"><%= @entry.public_id %></a> is already linked to
<a href="<%= edit_manuscript_path(@entry.manuscript) %>"><%= @entry.manuscript.public_id %></a>.
</p>