rails_app/config/routes.rb
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'

  get "/sparql-space", :to => "sparql#index"
  
  root :to => "catalog#index"

  resources :accounts, except: [:show] do
    collection do
      post 'add_to_group'
      post 'remove_from_group'
      post 'mark_as_reviewed'
      get 'search'
    end
  end

  resources :activities do
    collection {
      get 'index'
      get 'show_all'
    }
  end

  resources :pages, param: :name do
    member {
      post 'preview'
    }
  end

  resources :watches, only: [:create, :destroy, :update]
  resources :watches do
    collection {
      delete 'delete_many'
    }
  end
  resources :ratings, only: [:create, :destroy, :update]

  resources :groups do
    collection {
      get 'show_all'
    }
  end
  resources :group_users
  
  resources :dericci_records
  resources :dericci_games do
    collection {
      get 'stats'
    }
  end
  resources :dericci_links do
    collection {
      delete 'delete_many'
      put 'update_many'
    }
  end
  resources :dericci_notes, only: [:index]
  resources :dericci_sales, only: [:index]

  resources :replies
  #resources :notifications, only: [:index, :show, :update, :destroy]
  resources :notifications do
    collection {
      get 'read_many'
      delete 'delete_many'
    }
  end

  get '/dla/schoenberg', to: 'catalog#legacy'
  get '/dla/schoenberg/:path', to: 'catalog#legacy'
  get '/dla/schoenberg/feeds/search.rss', to: 'catalog#legacy'
  
  get '/bookmarks/export', to: 'bookmarks#export', as: 'export_bookmarks'
  get '/bookmarks/reload', to: 'bookmarks#reload', as: 'reload_bookmarks'
  resources :bookmarks do
    collection {
      delete 'delete_all', to: 'bookmarks#destroy'
      get 'check'
    }
    member {
      get 'addtag'
      get 'removetag'
    }
  end

  resources :downloads do
    collection {
      get 'index', as: "downloads"
    }
    member {
      get 'show' 
      get 'delete', action: :destroy
    }
  end

  # it would be cleaner to have :entries here and merge
  # CatalogController into EntriesController, but that doesn't work,
  # because Rails won't be able to find the catalog view files from
  # the blacklight gem.
  blacklight_for :catalog
  get "/advanced/", to: 'advanced#index'

  resources :comments do
    collection {
      post 'mark_as_reviewed'
      get 'search'
    }
  end

  # these should probably be removed, no?
  get "/faq/", to: 'community#faq', as: 'faq'
  get "/about/", to: 'community#about', as: 'about'
  get "/technical_overview/", to: 'community#technical_overview', as: 'technical_overview'
  get "/project_history/", to: 'community#project_history', as: 'project_history'
  get "/user_agreement/", to: 'community#user_agreement', as: 'user_agreement'
  get '/community/', to: 'community#show', as: 'community'
  get '/community/stats', to: 'community#stats'

  get '/dashboard/contributions'
  get '/dashboard/activity'
  get '/dashboard/forum'

#  resources :delayed_jobs, only: [:index]

#  resources '/messages/', to: 'private_messages#index', as: 'private_messages'

  resources :private_messages do
  end

  # Note here that we point #show to BL's CatalogController
  resources :entries, except: [:show] do
    collection {
      post 'calculate_bounds'
      post 'mark_as_approved'
      post 'add_to_group'
      post 'remove_from_group'
      get 'types'
      get 'import'
      post 'upload'
    }
    member {
      patch '/revert_confirm/', to: 'entries#revert_confirm'
      patch '/revert/', to: 'entries#revert'
      post 'deprecate'
      post 'compose'
      get 'verify'
      get 'history'
      get 'similar'
      get 'manuscript_candidates'
    }
  end
  get '/entries/:id.json', to: 'entries#show_json', defaults: { format: 'json' }
  get '/entries/:id', to: 'catalog#show'
  #get '/feed' => 'entries#feed'

  resources :entry_dates do
    collection {
      get 'parse_observed_date'
    }
  end

  resources :entry_manuscripts do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      put 'update_multiple'
    }
  end

  get '/feedback/', to: 'feedback#index', as: 'feedback'
  post '/feedback/', to: 'feedback#send_email', as: 'send_feedback'
  get '/feedback/thanks', to: 'feedback#thanks', as: 'feedback_thanks'

  resources :languages do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'history'
      get 'merge'
      post 'merge'
      patch '/revert_confirm/', to: 'languages#revert_confirm'
      patch '/revert/', to: 'languages#revert'
    end
  end

  get '/linkingtool/entry/:id', to: 'linking_tool#by_entry', as: 'linking_tool_by_entry'
  get '/linkingtool/manuscript/:id', to: 'linking_tool#by_manuscript', as: 'linking_tool_by_manuscript'

  # helpful for debugging
  get '/login_as/:username', to: 'accounts#login_as', as: 'login_as'

  resources :manuscripts do
    collection do
      post 'mark_as_reviewed'
      get 'search'
    end
    member do
      get 'table'
      get 'citation'
      get 'entry_candidates'
      get 'manage_entries'
      get 'history'
      get 'edit', action: :show
    end
  end

  resources :names do
    collection do
      post 'mark_as_reviewed'
      get 'search'
      get 'suggest'
      get 'more_like_this'
      get 'problems'
    end
    member do
      patch '/revert_confirm/', to: 'names#revert_confirm'
      patch '/revert/', to: 'names#revert'
      get 'history'
      get 'merge'
      get 'timeline'
      post 'merge'
    end
  end

  resources :places do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'merge'
      post 'merge'
      get 'history'
      patch '/revert_confirm/', to: 'places#revert_confirm'
      patch '/revert/', to: 'places#revert'
    end
  end

  # use 'username' as identifier here for nicer URLs
  # 10-26-2017: have to specifically allow '.' character or else it gets used as the URL format
  get 'profiles/:username' => 'profiles#show', :constraints =>{:username =>/.*/}, :as => 'profile'
  
  resources :provenance do
    collection {
      get 'parse_observed_date'
    }
  end

  if !Rails.env.production?
    get '/raise_error/', to: 'debug#raise_error'
  end

  resources :sources do
    collection do
      post 'calculate_bounds'
      post 'mark_as_reviewed'
      get 'search'
      get 'similar'
      get 'conflict'
      get 'types'
    end
    member do
      get 'merge'
      post 'merge'
      get 'history'
      post 'update_status'
      patch '/revert/', to: 'sources#revert'
      patch '/revert_confirm/', to: 'sources#revert_confirm'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # matches unmatched path - needs to remain as LAST route
  
  match "*path", to: "errors#render_404", via: :all
end

rails_app/app/controllers/sources_controller.rb
class SourcesController < SearchableAuthorityController

  #include CalculateBounds
  include MarkAsReviewed
  include LogActivity

  include Revert

  wrap_parameters include: Source.attribute_names - ['created_at', 'created_by', 'updated_at', 'updated_by'] + ['source_agents']

  before_action :set_source, only: [:show, :edit, :update, :destroy, :update_status]

  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy, :search]

  respond_to :html, :json

  load_and_authorize_resource :only => [:edit, :update, :destroy, :merge]

  def new
    @source = Source.new
    respond_to do |format|
      format.html { render "edit" }
    end
  end

  # various date separators (hyphenated!)
  def search
    if params[:date]
      params[:date] = Array(params[:date])
      params[:date].map! do | date |
        date.gsub('-', '').gsub('/', '')
      end
    end
    if params[:agent]
      params[:agent_name] = params[:agent]
    end
    super
  end

  def create
    success = false
    ActiveRecord::Base.transaction do
      filtered = source_params_for_create_and_edit
      @source = Source.new(filtered)
      if @source.whether_mss == Source::TYPE_HAS_MANUSCRIPT_NO
        @source.status = Source::TYPE_STATUS_NO_MSS
      else
        @source.status = Source::TYPE_STATUS_TO_BE_ENTERED
      end
      success = @source.save_by(current_user)
      if success
        @transaction_id = PaperTrail.transaction_id
      end
    end
    respond_to do |format|
      format.json {
        if !success
          errors_data = @source.errors.messages
          render :json => { :errors => errors_data }, :status => :unprocessable_entity
        else
          render "show"
        end
      }
      format.html {
        render "show"
      }
    end
  end

  def show
    @details = search_result_format(@source)
  end

  def edit
    if @source.source_type_id == 8
      flash[:error] = "This source is a personal 'Provenance Observation' and cannot be edited."
      render "show"
    end
  end

  def update
    # for checking which source_agent counters to manually update
    agents = @source.source_agents.map(&:agent)
    success = false
    ActiveRecord::Base.transaction do
      if params[:source_type_id] && can?(:update_type, @source)
        @source.update_attribute(:source_type_id, params[:source_type_id].to_i)
      end
      filtered = source_params_for_create_and_edit
      success = @source.update_by(current_user, filtered)
      if success
        @transaction_id = PaperTrail.transaction_id
        # for some reason, certain ways of removing a source_agent.agent don't update the counter cache, so we do it manually here
      end
    end
    respond_to do |format|
      format.json {
        if !success
          errors_data = @source.errors.messages
          render :json => { :errors => errors_data }, :status => :unprocessable_entity
        else
          render "show"
        end
      }
      format.html {
        if success
          redirect_to source_path(@source)
        else
          render 'edit'
        end
      }
    end
  end

  # used for merge suggestions
  def similar
    get_similar

    respond_to do |format|
      format.json
    end
  end

  def model_class
    Source
  end

  # change the status of a Source
  def update_status
    new_status = params[:status]
    error = nil
    if Source::STATUS_TYPES.map(&:first).member? new_status
      @source.status = new_status
      @source.save
    else
      error = "Invalid status"
    end

    respond_to do |format|
      format.html {
        if error.blank?
          render nothing: true
        else
          render status: :unprocessable_entity, html: "Invalid status"
        end
      }
      format.json {
        if error.blank?
          render nothing: true
        else
          render status: :unprocessable_entity, json: { "errors" => { base: "Invalid status" } }
        end
      }
    end
  end

  # used in merge, public_view (i.e. a way of standardizing 'name', 'title', etc. I guess...)
  def search_name_field
    "title"
  end

  # returns JSON containing type constants
  def types
    data = {
#       'source_type' => SourceType.all.map { |source_type|
       'source_type' => SourceType.where.not(name: "provenance_observation").map { |source_type|
        hash = source_type.attributes
        hash['invalid_source_fields'] = Source.invalid_source_fields_for_source_type(source_type.name)
        hash['valid_roles_for_source_agents'] = SourceAgent.valid_roles_for_source_type(source_type.name)
        hash
      },
      'medium' => Source::MEDIUM_TYPES,
    }

    respond_to do |format|
      format.json {
        render json: data
      }
    end
  end

  #def show_for_merge(attributes)
  #  attributes.except('id', 'in_manuscript_table', 'deleted', 'hidden', 'created_at', 'created_by', 'updated_at', 'updated_by', 'entries_count', 'reviewed', 'reviewed_by', 'reviewed_at', 'source_type')
  #end

  def show_for_merge(attributes)
    attributes.except(:id, :in_manuscript_table, :selling_agent, :display_value, :location, :institution, :deleted, :hidden, :created_at, :created_by, :whether_mss, :updated_at, :updated_by, :entries_count, :reviewed, :reviewed_by, :reviewed_at, :source_type)
  end

  def merge
    @source = Source.find(params[:id])
    @target_id = params[:target_id]
    @target = nil
    
    @differences = {}
    show_for_merge(search_result_format(@source)).each { |f, v| @differences[f] = [v] }
        
    #params[:title] = @source.title
    #params[:date] = @source.date

    if @source.source_type.name == "personal_observation" || @source.source_type.name == "provenance_observation"
      flash[:error] = "You can't merge a Source of this type (Provenance or Personal Observation)."
      redirect_to source_path(@source)
    end

    get_similar
    if @target_id.present?
      if @target_id.to_i == @source.id
        @warning = "You can't merge a record into itself"
      elsif Source.find_by(id: @target_id).source_type != @source.source_type
        @warning = "You can only merge sources that are the same type, to avoid data loss"
      else
        @target = Source.find_by(id: @target_id)
        show_for_merge(search_result_format(@target)).each do |f, v|
          if @differences[f].present?
            @differences[f][1] = v; 
          else 
            @differences[f] = [nil, v] 
          end
        end
      end
    end
    if params[:confirm] == "yes"
      ActiveRecord::Base.transaction do
        @target.update_attributes(source_params_for_create_and_edit)
        id = @source.public_id
        @source.merge_into(@target)
        if params[:source_agent_id]
          # remove old source agents
          @target.source_agents.each { |sa| sa.update({:source_id => nil})}
          agent = SourceAgent.find(params[:source_agent_id])
          agent.update({:source_id => @target.id})
        end
        @transaction_id = PaperTrail.transaction_id
        @model = @target
        log_activity
        flash[:success] = "#{id} has been successfully merged into #{@target.public_id}"
      end
      Source.update_counters(@target.id, :entries_count => @target.entries.where(deprecated: false, draft: false).count - @target.entries_count)
      redirect_to source_path(@target)
    end
  end

  # we don't ever destroy anything, we just mark it as deleted
  def destroy
    error = nil
    if @source.entries.count.to_i == 0
      @source.deleted = true
      if !@source.save_by(current_user)
        error = @source.errors.to_s
      else
        @source.watches.destroy_all

        @source.source_agents.uniq.each do |source_agent|
          Name.decrement_counter(:source_agents_count, source_agent.agent_id)         
        end
      end
    elsif @source.entries.where(deprecated: true).count > 0
      error = "The source cannot be deleted because it is still used in some entries (including the following deprecated entries: #{@source.entries.where(deprecated: true).map(&:public_id).join(", ")})"
    else
      error = "The source cannot be deleted because it is still used in some entries"
    end

    # if we call respond_with(@entry), which is more rails-ish, the
    # response is a 302 to a #show, but jquery's ajax code gets stuck
    # in an redirect loop, deleting the object over and over again. So
    # we force-return a 200 with an empty body for JSON calls to this
    # action.
    respond_to do |format|
      format.json {
        if !error
          render :json => {}, :status => :ok
        else
          render status: :unprocessable_entity, json: { "error" => error }
        end
      }
    end
  end

  def conflict
    get_conflicts

    respond_to do |format|
      format.json
    end
  end

  private

  def get_similar
    type = @source.source_type || 99
    s = Sunspot.more_like_this(@source) do
      fields(:title, :date => 10, :agent_name => 6)
      with :source_type, type
      paginate page: 1, per_page: 10
      order_by :score, :desc
      boost true
    end
    @similar = s.results
  end

  def get_conflicts
    filtered = source_params_for_create_and_edit
    title = filtered['title']
    date = filtered['date']

    query = Source.none

    if date.present? || title.present?
      query = Source.all

      if date.present?
        # use only the year so we get broadest possible matches
        broad_date = date.dup
        broad_date = broad_date[0..3] if broad_date.length > 3
        query = query.where("date LIKE ?", "#{broad_date}%")
      end

      if title.present?
        # NOTE: the order in which we add criteria to query seems to
        # make a difference in performance.

        # remove leading and trailing quotation marks and apostrophes
        words = title.split.select { |word| word.length > 3 }.map { |word| word.gsub(/^['"]/, '').gsub(/['"]$/, '') }

        words = words.map { |word| word.gsub(/"/, '\"') }

rails_app/app/views/sources/_instructions.html.erb
<p>This page allows you to update or edit your <b>Sources</b>. Your <b>Sources</b> appear in the queue below in reverse chronological order by default. Use the search box to locate specific <b>Sources</b> or groups of <b>Sources</b>.</p>
<p>Click <b class='btn btn-xs btn-success'>Edit</b> to edit the data related to that <b>Source</b>. Click <b class="btn btn-xs btn-primary">Add an Entry</b> to create a new entry for that <b>Source</b>. Click <b class="btn btn-xs btn-danger">Delete</b> to delete that <b>Source</b> from the database. Click <b class="btn btn-xs btn-info">Merge</b> to merge that <b>Source</b> with another source. The <b>ID</b> column to the right of the <b>Options</b> column displays the <b>SDBM Source ID Number</b> for each <b>Source</b>. Click on the <b>Source ID Number</b> to open that <b>Source’s</b> About page.</p>

rails_app/app/views/sources/_preview.html.erb
<% source = record %>
<div class="panel-heading">
    <strong class="h4"><%= link_to source.public_id, source_path(source) %></strong>
    <% if !source.reviewed %>
          <span class="text-warning"><span class="glyphicon glyphicon-alert"></span> Unapproved</span>
    <% end %>
</div>
<div class="panel-body">
<dl class="document-metadata">

        <dt>Type</dt>
        <dd>
            <% if source.source_type.present? %>
                <%= source.source_type.display_name %>
          <% end %>
        </dd>

        <% if source.date.present? %>
            <dt>Date</dt>
            <dd><%= format_fuzzy_date(source.date) %></dd>
        <% end %>
        
            <dt>Title</dt>
            <dd><%= source.title %></dd>

        <% if (author = source.author).present? %>
            <dt>Author</dt>
            <dd><%= source.author %></dd>
        <% end %>
        
        <% if (institutions = source.get_institutions).present? %>
        <dt>Institution</dt>
            <% institutions.each do |institution| %>
                <dd>
                    <% if institution.agent %>
                        <a class='badge' href="<%= url_for institution.agent %>"><%= institution.agent.name %></a>
                    <% end %>
                    <%= "(#{institution.observed_name})" if institution.observed_name %></dd>
            <% end %>
        <% end %>

        <% if (selling_agents = source.get_selling_agents).present? %>
        <dt>Selling Agent</dt>
            <% selling_agents.each do |selling_agent| %>
                <dd>
                    <% if selling_agent.agent %>
                        <a class='badge' href="<%= url_for selling_agent.agent %>"><%= selling_agent.agent.name %></a>
                    <% end %>
                    <%= "(#{selling_agent.observed_name})" if selling_agent.observed_name %></dd>
            <% end %>
        <% end %>

        <% if (sellers_or_holders = source.get_sellers_or_holders).present? %>
        <dt>Seller</dt>
            <% sellers_or_holders.each do |seller_or_holder| %>
                <dd>
                    <% if seller_or_holder.agent %>
                        <a class='badge' href="<%= url_for seller_or_holder.agent %>"><%= seller_or_holder.agent.name %></a>
                    <% end %>
                    <%= "(#{seller_or_holder.observed_name})" if seller_or_holder.observed_name %></dd>
            <% end %>
        <% end %>

<!--        <dt>Contains Manuscripts</dt>
            <dd><%= source.whether_mss||"Unknown" %></dd>-->

        <dt># Entries</dt>
            <dd>This source has <a target="_blank" class='badge' href="<%= search_advanced_path(source: source.public_id) %>"><%= SDBMSS::Util.to_many(source.entries.count, "entry") %></a> in the database.</dd>
<% if !defined?(abbreviate) || !abbreviate %>
<% if source.medium.present? || source.date_accessed.present? || source.location_institution.present? || source.location.present? || source.link.present? %>
        <% if source.medium.present? %>
        <dt>Method of Access</dt>
            <dd><%= source.medium_for_display %></dd>
        <% end %>

        <% if source.date_accessed.present? %>
        <dt>Date Accessed</dt>
            <dd><%= format_fuzzy_date(source.date_accessed) %></dd>
        <% end %>
        
        <% if source.location_institution.present? %>
        <dt>Institution</dt>
            <dd><%= source.location_institution %></dd>
        <% end %>

        <% if source.location.present? %>
        <dt>City, Country</dt>
            <dd><%= source.location %></dd>
        <% end %>

        <% if source.link.present? %>
        <dt>Online Link/<br/>Call No.</dt>
            <dd><a href="<%= source.link %>"><%= source.link %></a></dd>
        <% end %>

<% end %>

        <dt>Created By</dt>
            <dd><%= render partial: "shared/username_with_profile_link", locals: { user: source.created_by } %></dd>

        <dt>Status</dt>
            <dd><%= source.status||"Unknown" %></dd>

        <dt>Other Info</dt>
            <dd><%= source.other_info || "No other info recorded" %></dd>

</dl>

<% end %>
<div class="text-center text-muted">
  <span class="glyphicon glyphicon-time"></span> Added On <%= source.created_at.to_formatted_s(:long) %>
</div>
</div>

rails_app/app/views/sources/merge.html.erb
<%= content_for :head do %>
    <%= stylesheet_link_tag "extras", media: "all" %>
    <%= javascript_include_tag "extras" %>
<% end %>

<% content_for :breadcrumbs do %>
    <% @model = @source %>
    <%= render partial: "manage_models/breadcrumbs" %>
<% end %>

<div class="col-sm-12">
    <h2 class='h2 text-center'>Merge <%= @source.public_id %> &#10132; <%= @target.present? ? @target.public_id : "???" %></h2>
</div>

<div class="col-sm-12">
    <p>It is possible that two separate <b>Source</b> records may be created that represent the exact same <b>Source</b>. When this occurs, it is necessary to merge the two <b>Source</b> records into a single record. This eliminates redundancy and facilitates findability within the database.</p>
    <p>Merging <b>Sources</b> is an advanced function within the database. When you merge a <b>Source</b> into another one, Entries associated with the Source to be merged will be added to those associated with the remaining <b>Source</b>. The merged <b>Source</b> will be deleted forever and cannot be recovered. Exercise extreme caution when merging. Use this function only when you are completely certain that the two Source records represent the exact same <b>Source</b>.</p>
    <p class="text-info">Note: you will not be able to merge two <b>Source</b> records that are identified as different source types. If a source type has been incorrectly identified, it will be necessary to manually re-enter the records from the incorrect Source to the correct <b>Source</b>. Contact an administrator in these instances at <a href="mailto:sdbm@upenn.edu">sdbm@upenn.edu</a>.</p>
</div>

<div class="col-sm-5">
        <% if @target.present? %>
            <%= render partial: "sources/edit", locals: { source: @source, index: 0 } %>
        <% else %>
            <div class="panel-body"><%= render partial: "sources/source_details", locals: {source: @source} %></div>
        <% end %>
</div>
<%= form_tag(request.path, method: :post, class: "form-horizontal sdbmss-form") do %>
<div class='col-sm-2 text-center'>
    <% if @target %>
    <div class="">
        <div class="panel-body text-center">
            <input type="hidden" name="confirm" value="yes"/>
            <input type="hidden" name="target_id" value="<%= @target.id %>"/>
            <div><span class="h3">Confirm</span></div>
            <p>Are you sure? <strong><%= @source.public_id %></strong> will be <strong class="text-danger">deleted.</strong></p>
            <button class="btn btn-primary">Yes</button>
            <a class="btn btn-warning" href="<%= merge_source_path(@source) %>">Cancel</a>
        </div>
    </div>
    <span class="glyphicon glyphicon-arrow-right chevron"></span>
    <!--<%= image_tag 'right-arrow.png', class: 'img img-responsive chevron' %>-->
    <div class="">
        <div class="panel-body text-center">
            <%= link_to "Swap Sources", merge_source_path(@target, :target_id => @source.id), class: 'btn btn-info' %>
        </div>
    </div>
    <% end %>
</div>
<!-- form tag for collecting the results of the merge request -->
<div class="col-sm-5">
    <% if @target_id.present? && @target.present? %>
        <%= render partial: "sources/edit", locals: { source: @target, index: 1 } %>
    <% else %>
        <% if @target_id.present? %>
            <div class='panel panel-danger'>
            <% if @warning.present? %>
                <div class="panel-heading"><%= @warning %></div>
            <% else %>
                <div class="panel-heading">Could not find record #<%= @target_id %></div>
            <% end %>
            </div>
        <% end %>
        <div class="text-center form-inline">
        <%= form_tag(request.path, method: :get, class: "form-horizontal form-inline sdbmss-form text-center") do %>
                <label class="control-label">Find by unique ID</label>
                <button class="btn btn-primary" id='select-specific'>Select</button>
                <input type="text" name="target_id" class="form-control" placeholder="Enter Source ID here..."></p>
        <% end %>
        </div>
        <% if @similar.present? %>
        <div class="table-responsive">
            <table class='table table-striped'>
              <thead>
                <tr>
                    <th></th>
                    <th>ID</th>
                    <th>Source Agent</th>
                    <th>Date</th>
                    <th>Entries</th>
                </tr>
              </thead>
              <tbody>
                <% @similar.each do |src| %>
                    <% if src.id != @source.id %>
                    <tr>
                        <td><a class='btn btn-primary' href="<%= source_path(id: @source.id)%>/merge?target_id=<%= src.id %>">Select</a></td>
                        <td><%= link_to src.id, source_path(src.id) %></td>
                        <td><%= src.source_agents[0].agent.name if src.source_agents.count > 0 %></td>
                        <td><%= format_fuzzy_date(src.date) %></td>
                        <td><a href="<%= search_advanced_path(source: src.public_id) %>"><%= src.entries.approved_only.count %> entries</a></td>
                    </tr>
                    <% end %>
                <% end %>
              </tbody>
            </table>
        </div>
        <% else %>
            <b>No suggested names found, use manual search above.</b>
        <% end %>
    <% end %>
</div>
<% end %>

rails_app/app/views/sources/show.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "extras", media: "all" %>
    <%= javascript_include_tag "extras" %>
<% end %>

<% content_for :control_tools do %>
    <%= render partial: "tools", locals: {source: @source, edit: false} %>
    <li>
        <%= link_to history_source_path(@source) do %>
            <span class="glyphicon glyphicon-list-alt"></span> View change history
        <% end %>
    </li>
    <li class="divider"></li>
    <% if !["provenance_observation", "observation"].include?(@model.source_type.name) || @model.created_by == current_user %>
    <li>
        <%= link_to (new_entry_path(source_id: @source.id)) do %>
            <span class="glyphicon glyphicon-plus"></span> Add Entry From <%= @source.public_id %>
        <% end %>
    </li>
    <% end %>
<% end %>
<% content_for :breadcrumbs do %>
    <% @model = @source %>
    <%= render partial: "manage_models/breadcrumbs", locals: {edit: false} %>
<% end %>

<div class="row">
    <div class="col-sm-12">
        <% if @source.problem === true %>
          <div class="alert alert-danger"><span class="lead"><span class="glyphicon glyphicon-warning-sign"></span> Warning!</span> This source has been flagged as problematic because the purpose or data recorded is uncertain. Use only if you have no other options. If you have information to help us better identify this Source, please leave a comment.</div>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        
            <dl class="document-show-heading dl-horizontal dl-invert">
                <dt></dt>
                <dd class='h2'><%= @source.public_id %></dd>
            </dl>
            <%= render partial: "source_details", locals: { source: @source, details: @details } %>
        
    </div>
    <div class="col-sm-6 comments">
        <h2 class='text-center'><span class="glyphicon glyphicon-comment"></span> Discussion</h2>
        <p class='text-muted text-center'>Share additional information about this source - your comments will be displayed publicly.</p>
        <%= render partial: "comments/show_all", locals: {comments: @source.comments.where(public: true), record: @source} %>
    </div>
</div>