rails_app/config/routes.rb
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'

  get "/sparql-space", :to => "sparql#index"
  
  root :to => "catalog#index"

  resources :accounts, except: [:show] do
    collection do
      post 'add_to_group'
      post 'remove_from_group'
      post 'mark_as_reviewed'
      get 'search'
    end
  end

  resources :activities do
    collection {
      get 'index'
      get 'show_all'
    }
  end

  resources :pages, param: :name do
    member {
      post 'preview'
    }
  end

  resources :watches, only: [:create, :destroy, :update]
  resources :watches do
    collection {
      delete 'delete_many'
    }
  end
  resources :ratings, only: [:create, :destroy, :update]

  resources :groups do
    collection {
      get 'show_all'
    }
  end
  resources :group_users
  
  resources :dericci_records
  resources :dericci_games do
    collection {
      get 'stats'
    }
  end
  resources :dericci_links do
    collection {
      delete 'delete_many'
      put 'update_many'
    }
  end
  resources :dericci_notes, only: [:index]
  resources :dericci_sales, only: [:index]

  resources :replies
  #resources :notifications, only: [:index, :show, :update, :destroy]
  resources :notifications do
    collection {
      get 'read_many'
      delete 'delete_many'
    }
  end

  get '/dla/schoenberg', to: 'catalog#legacy'
  get '/dla/schoenberg/:path', to: 'catalog#legacy'
  get '/dla/schoenberg/feeds/search.rss', to: 'catalog#legacy'
  
  get '/bookmarks/export', to: 'bookmarks#export', as: 'export_bookmarks'
  get '/bookmarks/reload', to: 'bookmarks#reload', as: 'reload_bookmarks'
  resources :bookmarks do
    collection {
      delete 'delete_all', to: 'bookmarks#destroy'
      get 'check'
    }
    member {
      get 'addtag'
      get 'removetag'
    }
  end

  resources :downloads do
    collection {
      get 'index', as: "downloads"
    }
    member {
      get 'show' 
      get 'delete', action: :destroy
    }
  end

  # it would be cleaner to have :entries here and merge
  # CatalogController into EntriesController, but that doesn't work,
  # because Rails won't be able to find the catalog view files from
  # the blacklight gem.
  blacklight_for :catalog
  get "/advanced/", to: 'advanced#index'

  resources :comments do
    collection {
      post 'mark_as_reviewed'
      get 'search'
    }
  end

  # these should probably be removed, no?
  get "/faq/", to: 'community#faq', as: 'faq'
  get "/about/", to: 'community#about', as: 'about'
  get "/technical_overview/", to: 'community#technical_overview', as: 'technical_overview'
  get "/project_history/", to: 'community#project_history', as: 'project_history'
  get "/user_agreement/", to: 'community#user_agreement', as: 'user_agreement'
  get '/community/', to: 'community#show', as: 'community'
  get '/community/stats', to: 'community#stats'

  get '/dashboard/contributions'
  get '/dashboard/activity'
  get '/dashboard/forum'

#  resources :delayed_jobs, only: [:index]

#  resources '/messages/', to: 'private_messages#index', as: 'private_messages'

  resources :private_messages do
  end

  # Note here that we point #show to BL's CatalogController
  resources :entries, except: [:show] do
    collection {
      post 'calculate_bounds'
      post 'mark_as_approved'
      post 'add_to_group'
      post 'remove_from_group'
      get 'types'
      get 'import'
      post 'upload'
    }
    member {
      patch '/revert_confirm/', to: 'entries#revert_confirm'
      patch '/revert/', to: 'entries#revert'
      post 'deprecate'
      post 'compose'
      get 'verify'
      get 'history'
      get 'similar'
      get 'manuscript_candidates'
    }
  end
  get '/entries/:id.json', to: 'entries#show_json', defaults: { format: 'json' }
  get '/entries/:id', to: 'catalog#show'
  #get '/feed' => 'entries#feed'

  resources :entry_dates do
    collection {
      get 'parse_observed_date'
    }
  end

  resources :entry_manuscripts do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      put 'update_multiple'
    }
  end

  get '/feedback/', to: 'feedback#index', as: 'feedback'
  post '/feedback/', to: 'feedback#send_email', as: 'send_feedback'
  get '/feedback/thanks', to: 'feedback#thanks', as: 'feedback_thanks'

  resources :languages do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'history'
      get 'merge'
      post 'merge'
      patch '/revert_confirm/', to: 'languages#revert_confirm'
      patch '/revert/', to: 'languages#revert'
    end
  end

  get '/linkingtool/entry/:id', to: 'linking_tool#by_entry', as: 'linking_tool_by_entry'
  get '/linkingtool/manuscript/:id', to: 'linking_tool#by_manuscript', as: 'linking_tool_by_manuscript'

  # helpful for debugging
  get '/login_as/:username', to: 'accounts#login_as', as: 'login_as'

  resources :manuscripts do
    collection do
      post 'mark_as_reviewed'
      get 'search'
    end
    member do
      get 'table'
      get 'citation'
      get 'entry_candidates'
      get 'manage_entries'
      get 'history'
      get 'edit', action: :show
    end
  end

  resources :names do
    collection do
      post 'mark_as_reviewed'
      get 'search'
      get 'suggest'
      get 'more_like_this'
      get 'problems'
    end
    member do
      patch '/revert_confirm/', to: 'names#revert_confirm'
      patch '/revert/', to: 'names#revert'
      get 'history'
      get 'merge'
      get 'timeline'
      post 'merge'
    end
  end

  resources :places do
    collection {
      post 'mark_as_reviewed'
      get 'search'
      get 'more_like_this'
    }
    member do
      get 'merge'
      post 'merge'
      get 'history'
      patch '/revert_confirm/', to: 'places#revert_confirm'
      patch '/revert/', to: 'places#revert'
    end
  end

  # use 'username' as identifier here for nicer URLs
  # 10-26-2017: have to specifically allow '.' character or else it gets used as the URL format
  get 'profiles/:username' => 'profiles#show', :constraints =>{:username =>/.*/}, :as => 'profile'
  
  resources :provenance do
    collection {
      get 'parse_observed_date'
    }
  end

  if !Rails.env.production?
    get '/raise_error/', to: 'debug#raise_error'
  end

  resources :sources do
    collection do
      post 'calculate_bounds'
      post 'mark_as_reviewed'
      get 'search'
      get 'similar'
      get 'conflict'
      get 'types'
    end
    member do
      get 'merge'
      post 'merge'
      get 'history'
      post 'update_status'
      patch '/revert/', to: 'sources#revert'
      patch '/revert_confirm/', to: 'sources#revert_confirm'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # matches unmatched path - needs to remain as LAST route
  
  match "*path", to: "errors#render_404", via: :all
end

rails_app/app/controllers/accounts_controller.rb
# We have an 'Accounts' resource b/c devise uses 'Users' by default
# and combining all the stuff we want to be able to do with User
# models into a single controller makes things hairy.
class AccountsController < SearchableAuthorityController

  include MarkAsReviewed
  include AddToGroup

  before_action :require_admin, only: [:index, :new, :create, :edit, :destroy, :login_as]

  def model_class
    User
  end

  def search_model_class
    User
  end

  def resource_name
    "accounts"
  end

  def login_as
    if can? :manage, User
      user = User.find_by(username: params[:username])
      if user.present?
        sign_in(:user, user)
        redirect_to dashboard_contributions_path
      else
        render body: "ERROR: User not found: #{params[:username]}"
      end
    else
      render :status => :forbidden
    end
  end

  # overrides the default 'add_to_group' (and remove) since this is the USER half of things; but otherwise it's the same
  def add_to_group
    ids = params[:ids]
    group = Group.find(params[:group_id])
    if ids.present?
      users = User.where(id: ids)
      users.each do |u|
        GroupUser.create(user: u, group: group, created_by: current_user)
        if current_user != u
          u.notify(
            "#{current_user.to_s} has added you to user group: #{group.name}",
            group, 
            "group"
          )
        else
          group.admin.each do |admin|
            admin.notify(
              "#{current_user.to_s} has requested to be added to the user group: #{group.name}",
              group,
              "group"
            )
          end
        end
      end
      if users.count === 1 && users.first === current_user
        flash[:notice] = "Request sent!"
      else
        flash[:notice] = "#{"Invitation".pluralize(users)} sent!"
      end
    end
    respond_to do |format|
      format.json { render :json => {}, :status => :ok }
      format.html {
        if users
          flash.now[:success] = "Group membership pending for #{users.map(&:username).join(', ')}."
        end        
        redirect_to group_path(group) 
      }
    end
  end

  def remove_from_group
    ids = params[:ids]
    group = Group.find(params[:group_id])
    group.group_users.where(:user_id => ids).destroy_all
    respond_to do |format|
      format.json { render :json => {}, :status => :ok }
    end
  end

  def do_update
    if model_class.column_names.include?("encrypted_password") && model_params[:password].blank?
      result = @model.update_without_password(model_params)
      @model.updated_by = current_user
    else
      result = super
    end
    result
  end

  private

  # override from ManageModelsController: use profile#show
  def model_path(id)
    profile_path(@model.username)
  end

  def require_admin
    authorize! :manage, User
  end

  def model_params
    params.require(model_class_lstr.to_sym).permit(:active_survey, :username, :fullname, :institutional_affiliation, :email, :email_is_public, :password, :password_confirmation, :role, :bio, :active, :backup,
      :notification_setting_attributes => [
        :id, :user_id, :on_update, :on_comment, :on_reply, :on_message, :on_new_user, :on_group, :on_forum_post,
        :email_on_new_user, :email_on_update, :email_on_comment, :email_on_reply, :email_on_message, :email_on_group, :email_on_forum_post
        ]
      )
  end

end

rails_app/app/views/accounts/_breadcrumbs.html.erb
<% if can? :manage, User %>
    <li class=" ">
        <a href="/accounts">Manage Accounts</a>
    </li>
<% else %>
    <li class="breadcrumb">
        <a href="/community">Community</a>
    </li>
<% end %>
<li class=" <%= edit ? '' : 'active' %>">
  <a href="<%= profile_path(@model.username) %>"><%= @model %>
  </a>
</li>
<% if can? :edit, @model %>
<li class=" <%= edit ? 'active' : '' %>">
  <a href="<%= edit_account_path(@model) %>">Edit <%= @model %></a>
</li>
<% end %>

rails_app/app/views/accounts/_form.html.erb
<% url = @model.persisted? ? account_path(@model) : accounts_path %>
<%= form_for(@model, url: url, html: { class: "form-horizontal" }) do |f| %>
  <%= render partial: "errors" %>

  <div class="field form-group row">
      <%= f.label :username, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.text_field :username, :class => 'form-control' %>
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :fullname, "Full Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.text_field :fullname, :class => 'form-control' %>
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :institutional_affiliation, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.text_field :institutional_affiliation, :class => 'form-control' %>
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.email_field :email, :class => 'form-control' %>
      </div>
  </div>
  <div class="field form-group row">
      <div class="col-sm-2"></div>
      <div class="col-sm-4">
          <label>
              <%= f.check_box :email_is_public %> Email address is publicly visible
          </label>
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.password_field :password, :class => 'form-control' %>
      </div>
      <div class="col-sm-4 label-alignment">
          Leave blank to leave password unchanged
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.password_field :password_confirmation, :class => 'form-control' %>
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :bio, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.text_area :bio, :class => 'form-control' %>
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :role, class: "col-sm-2 control-label" %>
      <div class="col-sm-2">
          <%= f.collection_select :role, User::ROLES, :to_s, :to_s, {}, { :class => 'form-control' } %>
      </div>
  </div>
  <div class="field form-group row">
      <%= f.label :active, "Active", class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <label>
              <%= f.check_box :active %> User is allowed to log in
          </label>
      </div>
  </div>
  <div class="actions row">
      <div class="col-sm-4 col-sm-offset-2">
          <%= f.submit :class => 'btn btn-primary' %>
      </div>
  </div>
<% end %>

rails_app/app/views/accounts/_index_js.html.erb
<script type="text/javascript">

 $(document).ready(function() {

     var showInactive = "<%= params[:show_inactive] %>";
     var resourceName = "<%= resource_name %>";

     // flag = show all records, or only those that the user created
     <% if can? :manage, model_class  %>
     var showOnlyRecordsCreatedByUser = 0;
     <% else %>
     var showOnlyRecordsCreatedByUser = 1;
     <% end %>

     // Subclass of SDBM.ManageRecords tailored for display of accounts (ie users)
     var ManageAccounts = function(options) {
         SDBM.ManageRecords.call(this, options);
         var manageRecords = this;
     };

    SDBM.ManageRecords.prototype.setFormStateFromURL = function() {
        var manageRecords = this;
        var qs = new URI().query(true);

         $(".search-block").each(function(idx, element) {
             var search_field = $(element).find("select[name='search_field']").first();
             var search_value = $(element).find("input[name='search_value']").first();
             var populated = false;
             search_field.children().each(function (idx, option) {
                 if(!populated && qs[option.value] && qs[option.value].length > 0) {
                     search_field.val(option.value);
                     if (Array.isArray(qs[option.value]) && qs[option.value].length > 0) {
                         search_value.val(qs[option.value].pop());
                         if (qs[option.value].length == 0) qs[option.value] = undefined;
                     } else if ( qs[option.value] != undefined ) {
                        search_value.val(qs[option.value]);
                        qs[option.value] = undefined;
                     }

                     //delete qs[option.value];
                     populated = true;
                 }
             });
         });
        if(qs.unreviewed_only === '1') {
            $("input[name='unreviewed_only']").prop('checked', true);
        }
        manageRecords.showOrHideMarkCheckedRecordsButton();
    };
     
     ManageAccounts.prototype = Object.create(SDBM.ManageRecords.prototype);

     ManageAccounts.prototype.oldCreateSearchParams = ManageAccounts.prototype.createSearchParams;
     ManageAccounts.prototype.createSearchParams = function (dt_params) {
        var query = this.oldCreateSearchParams(dt_params);
        if (!$("input[name='inactive_only']").prop('checked')) {
            query.active = true;
        }
        return query;
     }

     ManageAccounts.prototype.getColumns = function() {
        var manageRecords = this;

        return [
            {
                sdbmssMinWidth: "20px",
                sdbmssMaxWidth: "20px",
                title: '<input type="checkbox" id="select-all" class="hideIfReviewed">',
                className: 'text-center unreviewed_only',
                orderable: false,
                render: function (data, type, full, meta) {
                    //if(manageRecords.getUnreviewedOnly() === 1) {
                        return '<input type="checkbox" name="review" value="' + full[manageRecords.dataTable.getColumnIndex("ID")] + '"/>';
                    //}
                    //return '';
                }
            },
            {
                sdbmssMinWidth: "120px",
                sdbmssMaxWidth: "120px",
                title: 'Options',
                orderable: false,
                render: function (data, type, full, meta) {
                    var str = '<a class="btn btn-xs btn-success" href="/' + manageRecords.options.resourceName + '/' + data + '/edit/">Edit</a> '
                    return str;
                }
            },
            {
                sdbmssMinWidth: "50px",
                sdbmssMaxWidth: "50px",
                title: 'ID',
                dbSortField: 'id',
                render: function (data) {
                    return '<a href="/accounts/' + data + '/edit">' + data + '</a>';    
                } 
            },
            {
                sdbmssMinWidth: "150px",
                sdbmssMaxWidth: "150px",
                title: 'Username',
                dbSortField: manageRecords.options.searchNameField,
                render: function (data, type, full, meta) {
                    return '<a href="/profiles/' + data + '/">' + data + '</a>';
                }
            },
            {
                sdbmssMinWidth: "150px",
                sdbmssMaxWidth: "150px",
                title: 'Fullname',
                dbSortField: 'fullname'
            },
            {
                sdbmssMinWidth: "150px",
                sdbmssMaxWidth: "150px",
                title: 'User Level',
                dbSortField: 'role'
            },
            {
                title: 'User Groups',
                dbSortField: 'groups',
                render: function (data, type, full, meta) {
                    data = JSON.parse(data);
                    var result = "";
                    for (var i = 0; i < data.length; i++) {
                        result += '<a target="_blank" href="/groups/' + data[i][0] + '">' + data[i][1] + '</a> ';
                    }
                    return result;
                }
            },
            {
                sdbmssMinWidth: "100px",
                sdbmssMaxWidth: "100px",
                title: 'Active',
                dbSortField: 'active'
            },
            {
                sdbmssMinWidth: "100px",
                sdbmssMaxWidth: "100px",
                title: 'Approved',
                dbSortField: 'reviewed'
            },
            {
                sdbmssMinWidth: "100px",
                sdbmssMaxWidth: "100px",
                title: 'Added On',
                dbSortField: 'created_at'
            },
            {
                sdbmssMinWidth: "100px",
                sdbmssMaxWidth: "100px",
                title: 'Last Active',
                dbSortField: 'last_sign_in_at'
            }/*,
            {
                sdbmssMinWidth: "100px",
                sdbmssMaxWidth: "100px",
                title: 'Created By',
                dbSortField: 'created_by_id'
            }*/
        ];
     };

     ManageAccounts.prototype.searchResultToTableRow = function (result) {
         return [ null, result.id, result.id, result[this.options.searchNameField], result.fullname, result.role, result.groups, result.active.toString(), result.reviewed.toString(), result.created_at, result.last_sign_in_at ];
     };


     new ManageAccounts({
         resourceName: "<%= resource_name %>",
         resourceNameSingular: "<%= resource_name.singularize %>",
         resourceNamePlural: "<%= resource_name.pluralize %>",
         showOnlyRecordsCreatedByUser: showOnlyRecordsCreatedByUser,
         searchNameField: "username",
         showActiveOnly: showInactive ? false : true
     });

 });

</script>

rails_app/app/views/accounts/_instructions.html.erb
<p>All SDBM <b>User Accounts</b> appear in the queue below in reverse chronological order from when the user created their <b>Account</b> (by default). Use the search box(es) to locate a specific <b>User Account</b>.</p>
<p>Click <b class="btn btn-success btn-xs">Edit</b> to edit the data related to that <b>User Profile</b>. The <b>ID</b> column to the right of the <b>Options</b> column displays the <b>SDBM User ID Number</b> for each <b>User Account</b>. Click on the <b>User ID Number</b> to edit the data related to that <b>User Account</b>.</p>

rails_app/app/views/accounts/_links.html.erb
<%= link_to 'Show', profile_path(@model.username) %> |
<%= link_to 'Go to Listing', models_path %>

rails_app/app/views/accounts/edit.html.erb
<%= stylesheet_link_tag "extras", media: "all" %>

<% model_id = @model.respond_to?(:public_id) ? @model.send(:public_id) : model_class.to_s + " record #" + @model.id.to_s %>

<% @page_title = "Edit #{model_id} - " + application_name %>

<% content_for :breadcrumbs do %>
  <%= render partial: "breadcrumbs", locals: {edit: true} %>
<% end %>

<h1 class='alert alert-danger'>Editing <%= model_id %></h1>

<%= render 'form' %>

rails_app/app/views/accounts/new.html.erb
<%= stylesheet_link_tag "extras", media: "all" %>

<h1>New <%= resource_name.singularize.capitalize %></h1>

<%= render 'form' %>